[package]
name = "memcache-proto"
description = "Memcached binary protocol"
version = "0.0.1"
authors = ["svartalf <self@svartalf.info>"]
keywords = ["memcached", "memcache", "binary", "protocol"]
categories = []

[dependencies]
enum_primitive = "0.1.1"
bytes = "0.4.5"
byteorder = "1.1.0"
num-traits = "0.1.40"

clippy = { version = "^0.0", optional = true }

[badges]
travis-ci = { repository = "https://github.com/svartalf/rust-memcache-proto", branch = "master" }
